import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Roboto } from "next/font/google";
import { CartProvider } from "@/contexts/cart-context";
import { SettingsProvider } from "@/contexts/settings-context";

const roboto = Roboto({
    weight: "400",
    subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
    title: "Brobar",
    description: "Generated by create next app",
    icons: {
        icon: "/favicon.webp"
    }
};

import { PreloaderProvider } from "@/contexts/preloader-context";
import { SiteToaster } from "@/components/site-toaster";
import Preloader from "@/components/preloader";

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const defaultScheme = "dark";

    return (
        <html lang="en" className={defaultScheme} style={{ colorScheme: "dark" }}>
            <head>
            </head>
            <body className={roboto.className}>
                <SettingsProvider>
                    <PreloaderProvider>
                        <Preloader />
                        <ThemeProvider
                            attribute="class"
                            defaultTheme="system"
                            enableSystem
                            disableTransitionOnChange
                        >
                            <CartProvider>
                                {children}
                                <SiteToaster />
                            </CartProvider>
                        </ThemeProvider>
                    </PreloaderProvider>
                </SettingsProvider>
            </body>
        </html>
    );
}
