import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { CartProvider } from "@/contexts/cart-context";
import { SettingsProvider } from "@/contexts/settings-context";

export const metadata: Metadata = {
    title: "Brobar",
    description: "Generated by create next app",
    icons: {
        icon: "/favicon.webp"
    }
};

import { PreloaderProvider } from "@/contexts/preloader-context";
import { SiteToaster } from "@/components/site-toaster";
import Preloader from "@/components/preloader";

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const defaultScheme = "dark";

    return (
        <html lang="uk" className={defaultScheme} style={{ colorScheme: "dark" }}>
            <head>
                <link
                    rel="preload"
                    href="/fonts/roboto-400.woff2"
                    as="font"
                    type="font/woff2"
                    crossOrigin="anonymous"
                />
                <link
                    rel="preload"
                    href="/fonts/roboto-500.woff2"
                    as="font"
                    type="font/woff2"
                    crossOrigin="anonymous"
                />
                <link
                    rel="preload"
                    href="/fonts/roboto-700.woff2"
                    as="font"
                    type="font/woff2"
                    crossOrigin="anonymous"
                />
            </head>
            <body>
                <SettingsProvider>
                    <PreloaderProvider>
                        <Preloader />
                        <ThemeProvider
                            attribute="class"
                            defaultTheme="dark"
                            forcedTheme="dark"
                            disableTransitionOnChange
                        >
                            <CartProvider>
                                {children}
                                <SiteToaster />
                            </CartProvider>
                        </ThemeProvider>
                    </PreloaderProvider>
                </SettingsProvider>
            </body>
        </html>
    );
}
